CREATE DATABASE `agenda`;
USE agenda;
CREATE TABLE `agenda`.`localidades` (
  `idLocalidad` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(100) NOT NULL,
  PRIMARY KEY (`idLocalidad`)
);

CREATE TABLE `agenda`.`tipos_de_contactos` (
`idTipo` int(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` varchar(100) NOT NULL,
  PRIMARY KEY (`idTipo`)
);

CREATE TABLE `agenda`.`domicilios` (
`idDireccion` int(11) NOT NULL AUTO_INCREMENT,
  `Calle` varchar(100) NOT NULL,
`Altura` varchar(6) ,
`piso` varchar(6) ,
`departamento` varchar(6) ,
`localidadId` int(11) NOT NULL,
FOREIGN KEY (`localidadId`) REFERENCES localidades(`idLocalidad`),
  PRIMARY KEY (`idDireccion`)
);

CREATE TABLE `agenda`.`personas` 
(
  `idPersona` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(45) NOT NULL,
  `Telefono` varchar(20) NOT NULL,
  `CorreoElectronico` varchar(60),
  `FechaCumpleanios` date,
`tipoContactoId` int(11),
`domicilioId` int(11),
  PRIMARY KEY (`idPersona`),
  FOREIGN KEY (`domicilioId`) REFERENCES `agenda`.`domicilios`(`idDireccion`),
FOREIGN KEY (`tipoContactoId`) REFERENCES `agenda`.`tipos_de_contactos`(`idTipo`)
);

insert into localidades (Nombre)
values
('San Miguel'),
('17 de Agosto'),
('25 de Mayo'),
('9 de Julio / La Niña'),
('Acassuso'),
('Aguas Verdes'),
('Alberti'),
('Arenas Verdes'),
('Arrecifes'),
('Avellaneda'),
('Ayacucho'),
('Azul'),
('Bahía Blanca'),
('Bahía San Blas'),
('Balcarce'),
('Balneario Marisol'),
('Balneario Orense'),
('Balneario Reta'),
('Balneario San Cayetano'),
('Baradero'),
('Bella Vista'),
('Benito Juárez'),
('Berazategui'),
('Berisso'),
('Boulogne'),
('Bragado'),
('Brandsen'),
('Campana'),
('Capilla del Señor'),
('Capital Federal'),
('Capitán Sarmiento'),
('Carapachay'),
('Carhue'),
('Carhué'),
('Carlos Keen'),
('Carmen de Areco'),
('Carmen de Patagones'),
('Caseros'),
('Castelar'),
('Castelli'),
('Chacabuco'),
('Chascomús'),
('Chivilcoy'),
('City Bell'),
('Ciudadela'),
('Claromecó'),
('Colón'),
('Coronel Dorrego'),
('Coronel Pringles'),
('Coronel Suárez'),
('Darregueira'),
('Dunamar'),
('Escobar'),
('Ezeiza'),
('Florencio Varela'),
('Florida'),
('Fortín Mercedes'),
('Garin'),
('General Arenales'),
('General Belgrano'),
('General Madariaga'),
('General Villegas'),
('Gral. Daniel Cerri'),
('Gran Buenos Aires'),
('Guaminí'),
('Haedo'),
('Huanguelen'),
('Hurlingham'),
('Isla Martín García'),
('Ituzaingo'),
('Junín'),
('La Plata'),
('La Tablada'),
('Laferrere'),
('Lanus'),
('Laprida'),
('Las Flores'),
('Las Gaviotas'),
('Las Toninas'),
('Lima'),
('Lisandro Olmos'),
('Llavallol'),
('Lobos'),
('Lomas de Zamora'),
('Los Toldos - Gral. Viamonte'),
('Lucila del Mar'),
('Luis Guillón'),
('Luján'),
('Magdalena'),
('Maipú'),
('Mar Azul'),
('Mar Chiquita'),
('Mar de Ajó'),
('Mar de Cobo'),
('Mar del Plata'),
('Mar del Sud'),
('Mar del Tuyú'),
('Martinez'),
('Médanos / Laguna Chasicó'),
('Mercedes'),
('Merlo'),
('Miramar'),
('Monte Hermoso'),
('Moreno'),
('Morón'),
('Munro'),
('Navarro'),
('Necochea'),
('Nueva Atlantis'),
('Olavarría'),
('Olivos'),
('Open Door'),
('Ostende'),
('Pedro Luro'),
('Pehuajó'),
('Pehuen Có'),
('Pergamino'),
('Pigüé'),
('Pilar'),
('Pinamar'),
('Puan'),
('Punta Alta'),
('Punta Indio'),
('Punta Lara'),
('Quequén'),
('Quilmes'),
('Ramallo'),
('Ramos Mejía'),
('Ranchos'),
('Rauch'),
('Rivadavia'),
('Rojas'),
('Roque Pérez'),
('Saenz Peña'),
('Saladillo'),
('Salto'),
('San Antonio de Areco'),
('San Bernardo'),
('San Cayetano'),
('San Clemente del Tuyú'),
('San Fernando'),
('San Isidro'),
('San Justo'),
('San Martin'),
('San Miguel del Monte'),
('San Nicolás'),
('San Pedro'),
('San Vicente'),
('Santa Clara del Mar'),
('Santa Teresita'),
('Sarandí'),
('Sierra de la Ventana'),
('Sierra de los Padres'),
('Tandil'),
('Tapalqué'),
('Temperley'),
('Tigre'),
('Tornquist / Ruta Prov. 76'),
('Trenque Lauquen'),
('Tres Arroyos'),
('Turdera'),
('Valentin Alsina'),
('Vicente Lopez'),
('Victoria'),
('Villa Ballester'),
('Villa Gesell'),
('Villa Lynch'),
('Villa Serrana La Gruta'),
('Villa Ventana'),
('Villalonga'),
('Wilde'),
('Zárate');

insert into tipos_de_contactos (Descripcion)
values
('familia'),
('amigo'),
('universidad'),
('trabajo'),
('vecino');
